In [1]:
#TENSORTFLOW - to execute 6000*80*20 matrix within a second, KERAS
#DEEP LEARNING
#2-D,3-D
#BREAST CANCER
#HAND WRITING RECOGNITION FROM IMAGE
#SIGN RECOGNITION FOR DEF AND DUM

In [2]:
#importing libraries
import tensorflow as tf
import numpy as np
import pandas as pd

In [3]:
#constant -unchangeable
t1= tf.constant(3)
t1

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [4]:
#1-D
t1=tf.constant([1,2,3])
t1


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

# Constant- unchangable

In [6]:
#constant-2D
t2=tf.constant([[1,2,3],[4,5,6]])
t2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [7]:
#tensorflow is converted to numpy array
t2.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#shape of t2
t2.shape

TensorShape([2, 3])

In [9]:
#dimension of t2 is finding 
tf.rank(t2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# variable-changable

In [10]:
#variable tensorflow
tv1=tf.Variable(3,dtype=tf.float32,name='var1')
tv1 

<tf.Variable 'var1:0' shape=() dtype=float32, numpy=3.0>

In [12]:
#2D variable tensor
tv2=tf.Variable([[10,12,13],[6,9,5]],name='var1')
tv2

<tf.Variable 'var1:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 12, 13],
       [ 6,  9,  5]])>

In [13]:
tv2

<tf.Variable 'var1:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 12, 13],
       [ 6,  9,  5]])>

In [14]:
tv2[0]   #fetching using index value

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 12, 13])>

In [35]:
tv2[0,1]

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [36]:
tv2[0,1].assign(20)  #replacing the first row second column value
tv2

<tf.Variable 'var1:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 20, 13],
       [ 6,  9,  5]])>

In [ ]:
1-D value

In [45]:
tv3=tf.Variable([10,12,13,6,9,5],name='var1')  #1D value
tv3

<tf.Variable 'var1:0' shape=(6,) dtype=int32, numpy=array([10, 12, 13,  6,  9,  5])>

In [46]:
tv3[0] 

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [39]:
tv3[0:3]   # fetching index value from 0-3

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 12, 13])>

In [47]:
tv3[0].assign(20)  #replacing the first row second column value
tv3

<tf.Variable 'var1:0' shape=(6,) dtype=int32, numpy=array([20, 12, 13,  6,  9,  5])>

In [40]:
#creating normal distribution
#creating random value with normal distribution
tv3=tf.random.normal([4,3])
tv3

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.51234996,  1.8438705 , -0.9077294 ],
       [-0.68948233,  0.2821797 ,  0.5782067 ],
       [-0.7498854 , -0.578337  ,  0.02866211],
       [ 0.6782722 ,  0.22453335,  0.6456444 ]], dtype=float32)>

In [41]:
#creating 3*3 with ones
#default data type is float
tf.ones([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [42]:
#creating 3*3 with zeros
tf.zeros([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [48]:
#store the value in another variable
tv4=tf.Variable(tv3)
tv4

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([20, 12, 13,  6,  9,  5])>

In [50]:
#reshaping - we change only 3*2 to 2* 3  not into 4*4 it is error
tv2=tf.reshape(tv2,(3,2))
tv2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [13,  6],
       [ 9,  5]])>

# Arithmetic operation

In [56]:
tf1=tf.Variable([[10,12],[6,9]])
tf1

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10, 12],
       [ 6,  9]])>

In [57]:
tf2=tf.Variable([[1,2],[3,4]])
tf2

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [58]:
#addition
tf1+tf2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 14],
       [ 9, 13]])>

In [59]:
#subraction
tf1-tf2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 10],
       [ 3,  5]])>

In [60]:
#multiplication
tf1*tf2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 24],
       [18, 36]])>

In [61]:
# power- squaring
tf.pow(tf1,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 144],
       [ 36,  81]])>

In [66]:
#square root
tf1=tf.Variable([1.,2,3])
tf.sqrt(tf1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.       , 1.4142135, 1.7320508], dtype=float32)>

# dot product with tensor

In [69]:
#if axis=0 it takes first value and multiply with each value
a=tf.Variable([2.,3,4])
b=tf.Variable([3.,2,5])
tf.tensordot(a,b,0)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 6.,  4., 10.],
       [ 9.,  6., 15.],
       [12.,  8., 20.]], dtype=float32)>

In [92]:
c=tf.Variable([[2.,3,4],[3.,6,8.],[1,2,3]])
d=tf.Variable([[3.,2,5],[6.,8,3],[10,20,30]])
tf.tensordot(c,d,0)

<tf.Tensor: shape=(3, 3, 3, 3), dtype=float32, numpy=
array([[[[  6.,   4.,  10.],
         [ 12.,  16.,   6.],
         [ 20.,  40.,  60.]],

        [[  9.,   6.,  15.],
         [ 18.,  24.,   9.],
         [ 30.,  60.,  90.]],

        [[ 12.,   8.,  20.],
         [ 24.,  32.,  12.],
         [ 40.,  80., 120.]]],


       [[[  9.,   6.,  15.],
         [ 18.,  24.,   9.],
         [ 30.,  60.,  90.]],

        [[ 18.,  12.,  30.],
         [ 36.,  48.,  18.],
         [ 60., 120., 180.]],

        [[ 24.,  16.,  40.],
         [ 48.,  64.,  24.],
         [ 80., 160., 240.]]],


       [[[  3.,   2.,   5.],
         [  6.,   8.,   3.],
         [ 10.,  20.,  30.]],

        [[  6.,   4.,  10.],
         [ 12.,  16.,   6.],
         [ 20.,  40.,  60.]],

        [[  9.,   6.,  15.],
         [ 18.,  24.,   9.],
         [ 30.,  60.,  90.]]]], dtype=float32)>

In [71]:
#dot product- multiply only 1st row with 1ist row 
a=tf.Variable([2.,3,4])
b=tf.Variable([3.,2,5])
tf.tensordot(a,b,1)

<tf.Tensor: shape=(), dtype=float32, numpy=32.0>

In [86]:
a=tf.Variable([[3.,4],[6.,5]])
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[3., 4.],
       [6., 5.]], dtype=float32)>

In [87]:
#eigen values-square matrix
tf.linalg.eigvals(a)

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([-0.9999999+0.j,  9.       +0.j], dtype=complex64)>

In [94]:
tf.linalg.eigvals(c)

<tf.Tensor: shape=(3,), dtype=complex64, numpy=array([ 0.21234712+0.j,  0.45580184+0.j, 10.331851  +0.j], dtype=complex64)>

In [88]:
#determinant
tf.linalg.det(a)

<tf.Tensor: shape=(), dtype=float32, numpy=-9.0>

In [89]:
#finding tranpose of a
tf.transpose(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 6.],
       [4., 5.]], dtype=float32)>

# L